-- ============================================================
-- Migration: auditor workflow + photo evidence
-- Run once on the existing Neon database (SQL editor or psql).
-- ============================================================

-- 1. Audit verification state on the accommodation itself, so the public
--    directory/detail can show a "Geverifieerd" badge without a join.
--    none     = geen audit van toepassing / aangevraagd
--    pending  = verified-abonnement, audit loopt nog
--    verified = auditor heeft ter plaatse geverifieerd
ALTER TABLE accommodations
  ADD COLUMN IF NOT EXISTS audit_status VARCHAR(12) NOT NULL DEFAULT 'none'
  CHECK (audit_status IN ('none', 'pending', 'verified'));

ALTER TABLE accommodations
  ADD COLUMN IF NOT EXISTS verified_at TIMESTAMPTZ NULL;

-- 2. One audit per verification round for an accommodation.
CREATE TABLE IF NOT EXISTS audits (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  accommodation_id INTEGER NOT NULL REFERENCES accommodations (id) ON DELETE CASCADE,
  status           VARCHAR(12) NOT NULL DEFAULT 'available'
                    CHECK (status IN ('available', 'claimed', 'submitted', 'approved', 'rejected')),
  auditor_name     VARCHAR(160),
  auditor_email    VARCHAR(180),
  notes            TEXT,
  claimed_at       TIMESTAMPTZ,
  submitted_at     TIMESTAMPTZ,
  decided_at       TIMESTAMPTZ,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_audits_acc    ON audits (accommodation_id);
CREATE INDEX IF NOT EXISTS idx_audits_status ON audits (status);

-- 3. The auditor's verdict per criterion.
CREATE TABLE IF NOT EXISTS audit_answers (
  audit_id     INTEGER NOT NULL REFERENCES audits (id)   ON DELETE CASCADE,
  criterion_id INTEGER NOT NULL REFERENCES criteria (id) ON DELETE CASCADE,
  verdict      VARCHAR(8) NOT NULL DEFAULT 'na' CHECK (verdict IN ('pass', 'fail', 'na')),
  note         TEXT,
  PRIMARY KEY (audit_id, criterion_id)
);

-- 4. Evidence photos, linked to an audit + criterion.
--    url/public_id come from Cloudinary after a signed direct upload.
CREATE TABLE IF NOT EXISTS audit_photos (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  audit_id     INTEGER NOT NULL REFERENCES audits (id)   ON DELETE CASCADE,
  criterion_id INTEGER NOT NULL REFERENCES criteria (id) ON DELETE CASCADE,
  url          VARCHAR(500) NOT NULL,
  public_id    VARCHAR(255),
  uploaded_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_audit_photos_audit ON audit_photos (audit_id);

-- Keep updated_at fresh on audits.
DROP TRIGGER IF EXISTS trg_audits_updated ON audits;
CREATE TRIGGER trg_audits_updated
  BEFORE UPDATE ON audits
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
