-- ============================================================
-- Migration: verblijf-login via magic link
-- Run once on the existing Neon database (SQL editor of psql).
-- ============================================================

-- 1. Eenmalige inlogtokens (magic links). Kort geldig, eenmalig bruikbaar.
CREATE TABLE IF NOT EXISTS magic_tokens (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email       VARCHAR(180) NOT NULL,
  token_hash  VARCHAR(64)  NOT NULL,          -- sha256 van de token (nooit plain opslaan)
  expires_at  TIMESTAMPTZ  NOT NULL,
  used_at     TIMESTAMPTZ,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_magic_tokens_hash  ON magic_tokens (token_hash);
CREATE INDEX IF NOT EXISTS idx_magic_tokens_email ON magic_tokens (email);

-- 2. Sessies voor ingelogde verblijfseigenaren. De browser bewaart de sessie-
--    token (zoals nu de auditor/admin-sleutel) en stuurt 'm mee per verzoek.
CREATE TABLE IF NOT EXISTS owner_sessions (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email       VARCHAR(180) NOT NULL,
  token_hash  VARCHAR(64)  NOT NULL,          -- sha256 van de sessietoken
  expires_at  TIMESTAMPTZ  NOT NULL,
  created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_owner_sessions_hash ON owner_sessions (token_hash);
