-- Ecostay — database schema (PostgreSQL)
-- Runs automatically on first `docker compose up` (mounted in initdb.d),
-- or load manually with: psql "<connection-url>" -f db/schema.sql

DROP TABLE IF EXISTS assessment_answers CASCADE;
DROP TABLE IF EXISTS assessments       CASCADE;
DROP TABLE IF EXISTS accommodations    CASCADE;
DROP TABLE IF EXISTS criteria          CASCADE;
DROP TABLE IF EXISTS categories        CASCADE;

-- A theme a stay is scored on (energy, water, waste, ...).
CREATE TABLE categories (
  id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug   VARCHAR(60)  NOT NULL UNIQUE,
  name   VARCHAR(120) NOT NULL,
  intro  VARCHAR(255),
  sort   INTEGER      NOT NULL DEFAULT 0
);

-- A single checkable requirement, worth a number of points.
CREATE TABLE criteria (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id INTEGER NOT NULL REFERENCES categories (id) ON DELETE CASCADE,
  code        VARCHAR(20)  NOT NULL UNIQUE,   -- e.g. EN-01, shown to owners
  title       VARCHAR(200) NOT NULL,
  description VARCHAR(500),
  points      INTEGER      NOT NULL DEFAULT 1,
  sort        INTEGER      NOT NULL DEFAULT 0
);
CREATE INDEX idx_criteria_category ON criteria (category_id);

-- A place that can hold a certificate. level 0 = not (yet) certified.
CREATE TABLE accommodations (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug          VARCHAR(140) NOT NULL UNIQUE,
  name          VARCHAR(160) NOT NULL,
  type          VARCHAR(60)  NOT NULL DEFAULT 'B&B',
  city          VARCHAR(120) NOT NULL,
  country       VARCHAR(80)  NOT NULL DEFAULT 'Nederland',
  description   TEXT,
  website       VARCHAR(255),
  contact_email VARCHAR(180),
  image_url     VARCHAR(500),
  score         NUMERIC(5,2) NOT NULL DEFAULT 0,      -- 0..100
  level         SMALLINT     NOT NULL DEFAULT 0,      -- 0..3 leaves
  status        VARCHAR(10)  NOT NULL DEFAULT 'draft'
                 CHECK (status IN ('draft', 'certified')),
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_accommodations_level  ON accommodations (level);
CREATE INDEX idx_accommodations_status ON accommodations (status);

-- One completed self-assessment. The most recent one drives the stay's level.
CREATE TABLE assessments (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  accommodation_id INTEGER NOT NULL REFERENCES accommodations (id) ON DELETE CASCADE,
  score            NUMERIC(5,2) NOT NULL DEFAULT 0,
  level            SMALLINT     NOT NULL DEFAULT 0,
  submitted_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_assessments_acc ON assessments (accommodation_id);

-- Which criteria were met in a given assessment.
CREATE TABLE assessment_answers (
  assessment_id INTEGER NOT NULL REFERENCES assessments (id) ON DELETE CASCADE,
  criterion_id  INTEGER NOT NULL REFERENCES criteria (id)   ON DELETE CASCADE,
  met           BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (assessment_id, criterion_id)
);
CREATE INDEX idx_answers_criterion ON assessment_answers (criterion_id);

-- Keep updated_at fresh on every UPDATE of an accommodation.
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_accommodations_updated
  BEFORE UPDATE ON accommodations
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
